import React, { useEffect, useState } from 'react';
import { Button } from '../../components/ui/button';
import { Field, Input, Textarea } from '../../components/ui/input';
import { useAdminAuth } from '../../features/admin/AdminAuthContext';
import { listAdminCategories, saveCategory } from '../../repositories/adminCatalogRepository';
import type { AdminCategory } from '../../types/catalog';

const blank = { name: '', slug: '', description: '', is_active: true, display_order: 0 };
export function AdminCategoriesPage() {
  const { roles } = useAdminAuth(); const canManage = roles.some((role) => role === 'owner' || role === 'manager');
  const [items, setItems] = useState<AdminCategory[]>([]); const [form, setForm] = useState(blank); const [editing, setEditing] = useState<AdminCategory | null>(null); const [error, setError] = useState<string | null>(null);
  const load = () => void listAdminCategories().then(setItems).catch((cause: Error) => setError(cause.message));
  useEffect(load, []);
  async function submit(event: React.FormEvent) { event.preventDefault(); try { await saveCategory({ ...form, description: form.description || null, display_order: Number(form.display_order) }, editing?.id); setForm(blank); setEditing(null); load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not save category.'); } }
  return <section className="space-y-8"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-brand-500">Catalog</p><h1 className="mt-2 font-display text-3xl font-bold">Categories</h1>{!canManage ? <p className="mt-2 text-sm text-ink/60">View only — staff cannot change catalog data.</p> : null}</div>
    {canManage ? <form onSubmit={submit} className="grid gap-4 rounded-2xl border border-ink/10 bg-white p-5 sm:grid-cols-2"><Field label="Name" htmlFor="category-name"><Input id="category-name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /></Field><Field label="Slug" htmlFor="category-slug"><Input id="category-slug" value={form.slug} disabled={!!editing} onChange={(e) => setForm({ ...form, slug: e.target.value })} required /></Field><Field label="Display order" htmlFor="category-order"><Input id="category-order" type="number" min="0" value={form.display_order} onChange={(e) => setForm({ ...form, display_order: Number(e.target.value) })} required /></Field><label className="flex items-end gap-2 pb-3 text-sm"><input type="checkbox" checked={form.is_active} onChange={(e) => setForm({ ...form, is_active: e.target.checked })} /> Active</label><Field label="Description" htmlFor="category-description" className="sm:col-span-2"><Textarea id="category-description" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></Field><div className="flex gap-2 sm:col-span-2"><Button type="submit">{editing ? 'Save category' : 'Create category'}</Button>{editing ? <Button type="button" variant="ghost" onClick={() => { setEditing(null); setForm(blank); }}>Cancel</Button> : null}</div></form> : null}
    {error ? <p role="alert" className="text-sm text-red-700">{error}</p> : null}<div className="overflow-hidden rounded-2xl border border-ink/10 bg-white"><table className="w-full text-left text-sm"><thead className="bg-cream-dark text-ink/60"><tr><th className="p-4">Order</th><th className="p-4">Category</th><th className="p-4">Status</th>{canManage ? <th className="p-4" /> : null}</tr></thead><tbody>{items.map((item) => <tr key={item.id} className="border-t border-ink/10"><td className="p-4">{item.display_order}</td><td className="p-4"><strong>{item.name}</strong><span className="ml-2 text-ink/50">{item.slug}</span></td><td className="p-4">{item.is_active ? 'Active' : 'Inactive'}</td>{canManage ? <td className="p-4 text-right"><Button size="sm" variant="outline" onClick={() => { setEditing(item); setForm({ name: item.name, slug: item.slug, description: item.description ?? '', is_active: item.is_active, display_order: item.display_order }); }}>Edit</Button></td> : null}</tr>)}</tbody></table></div></section>;
}
